# -*- coding: utf-8 -*-
"""22F-3069_BCS-7F_FCV_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10k0pT5LUYmmmUW8vnXTfwK1eE9CZWIx7
"""

# Single-cell Colab pipeline: upload .zip (from PC), preprocess, classical features (HOG/ORB+SVM),
# transfer learning (EfficientNetB0), training graphs, and Grad-CAM explainability.
# Humanized, heavily commented, ready to run.

# === 0) Install / Import ===
!pip install -q tensorflow==2.19.0 scikit-image opencv-python-headless==4.9.0.80
# scikit-learn & matplotlib are preinstalled in Colab usually
import os, zipfile, glob, random, shutil, io, sys
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from skimage.feature import hog, local_binary_pattern
import cv2
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras import layers, models
from google.colab import files

print("Libraries loaded. TensorFlow version:", tf.__version__)

# === 1) Upload .zip dataset from your PC ===
# Click the button that appears to upload a single zip file containing class subfolders.
print("\nPlease upload a .zip file (dataset) from your PC now. The zip should have subfolders per class.")
uploaded = files.upload()              # user selects a file
if len(uploaded) == 0:
    raise SystemExit("No file uploaded. Re-run and upload your dataset zip.")

# Save uploaded file
uploaded_filename = list(uploaded.keys())[0]
print("Uploaded file:", uploaded_filename)

# Unzip into /content/dataset/
root_extract = "/content/dataset"
if os.path.exists(root_extract):
    shutil.rmtree(root_extract)
os.makedirs(root_extract, exist_ok=True)

with zipfile.ZipFile(uploaded_filename, 'r') as z:
    z.extractall(root_extract)

print("Unzipped to:", root_extract)

# Try to automatically discover top-level folder with classes
# We accept structure: dataset/<some-folder>/<class-folders...>  OR dataset/<class-folders...>
top_dirs = [p for p in sorted(glob.glob(os.path.join(root_extract, "*"))) if os.path.isdir(p)]
# pick candidate that contains subfolders which appear to be class names (i.e., containing images)
chosen_root = root_extract
for td in top_dirs:
    subdirs = [s for s in glob.glob(os.path.join(td, "*")) if os.path.isdir(s)]
    # check for jpg/png in subdirs
    if len(subdirs) > 0:
        # prefer one where subdir contains images
        found_images = False
        for sd in subdirs[:6]:
            if len(glob.glob(os.path.join(sd, "*.jpg"))) + len(glob.glob(os.path.join(sd, "*.png"))) > 0:
                found_images = True
                break
        if found_images:
            chosen_root = td
            break

print("Using dataset root:", chosen_root)
print("Classes found:", [os.path.basename(d) for d in sorted(glob.glob(os.path.join(chosen_root, "*"))) if os.path.isdir(d)][:10])

# === 2) Quick dataset summary & small visual sample (Module 1) ===
def list_image_counts(root):
    classes = [d for d in sorted(glob.glob(os.path.join(root, "*"))) if os.path.isdir(d)]
    return {os.path.basename(c): len(glob.glob(os.path.join(c, "*.jpg")))+len(glob.glob(os.path.join(c, "*.png"))) for c in classes}

counts = list_image_counts(chosen_root)
print("\nPer-class image counts (first 20 classes shown):")
for i, (cls, cnt) in enumerate(counts.items()):
    if i >= 20: break
    print(f"  {cls:20s} : {cnt}")

# show sample images
sample_imgs = []
for cls in list(counts.keys())[:6]:
    files_in_cls = glob.glob(os.path.join(chosen_root, cls, "*.jpg")) + glob.glob(os.path.join(chosen_root, cls, "*.png"))
    if files_in_cls:
        sample_imgs.append(files_in_cls[0])
plt.figure(figsize=(12,4))
for i, p in enumerate(sample_imgs):
    img = cv2.imread(p)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    plt.subplot(1, len(sample_imgs), i+1)
    plt.imshow(img); plt.title(os.path.basename(os.path.dirname(p)))
    plt.axis('off')
plt.suptitle("Example images from dataset (Module 1 visualization)")
plt.show()

# === 3) MODULE 1: Preprocessing helpers (noise, denoise, geometric transforms, edges) ===
def add_gaussian_noise(img, mean=0, sigma=20):
    gauss = np.random.normal(mean, sigma, img.shape).astype(np.float32)
    noised = img.astype(np.float32) + gauss
    noised = np.clip(noised, 0, 255).astype(np.uint8)
    return noised

def denoise_nlmeans(img):
    # expects uint8 BGR or RGB
    if img.ndim == 3:
        return cv2.fastNlMeansDenoisingColored(img, None, h=10, hColor=10, templateWindowSize=7, searchWindowSize=21)
    else:
        return cv2.fastNlMeansDenoising(img, None, 10, 7, 21)

def rotate_image(img, angle):
    h, w = img.shape[:2]
    M = cv2.getRotationMatrix2D((w/2,h/2), angle, 1.0)
    return cv2.warpAffine(img, M, (w,h))

def show_preprocessing_examples(img_path):
    img = cv2.imread(img_path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    noisy = add_gaussian_noise(img_rgb)
    denoised = denoise_nlmeans(noisy)
    gray = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)
    edges = cv2.Canny(gray, 80, 150)
    rot = rotate_image(img_rgb, 25)

    plt.figure(figsize=(12,6))
    plt.subplot(2,3,1); plt.imshow(img_rgb); plt.title("Original"); plt.axis('off')
    plt.subplot(2,3,2); plt.imshow(noisy); plt.title("Gaussian Noise"); plt.axis('off')
    plt.subplot(2,3,3); plt.imshow(denoised); plt.title("Denoised (NLMeans)"); plt.axis('off')
    plt.subplot(2,3,4); plt.imshow(rot); plt.title("Rotated"); plt.axis('off')
    plt.subplot(2,3,5); plt.imshow(edges, cmap='gray'); plt.title("Canny Edges"); plt.axis('off')
    plt.tight_layout()
    plt.show()

# show examples using first available image
first_class = list(counts.keys())[0]
first_img = glob.glob(os.path.join(chosen_root, first_class, "*.jpg")) + glob.glob(os.path.join(chosen_root, first_class, "*.png"))
if first_img:
    print("\nModule 1 preprocessing examples for class:", first_class)
    show_preprocessing_examples(first_img[0])

# === 4) MODULE 2: Classical feature extraction (HOG + ORB) and simple classifier (SVM)
# We'll collect a subset of images to keep runtime reasonable: if dataset is huge, sample a max per class.
MAX_PER_CLASS = 300   # adjust if you have more time / GPU
img_paths = []
labels = []
classes = sorted(list(counts.keys()))
for cls in classes:
    files_cls = glob.glob(os.path.join(chosen_root, cls, "*.jpg")) + glob.glob(os.path.join(chosen_root, cls, "*.png"))
    if not files_cls:
        continue
    sample = files_cls if len(files_cls) <= MAX_PER_CLASS else random.sample(files_cls, MAX_PER_CLASS)
    for f in sample:
        img_paths.append(f)
        labels.append(cls)

print(f"\nCollected {len(img_paths)} images for classical-features pipeline (Module 2).")

# HOG feature extractor (returns 1D vector)
def extract_hog_feature_gray(img, resize=(128,128)):
    im = cv2.resize(img, resize)
    gray = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY)
    fd, hog_image = hog(gray, orientations=9, pixels_per_cell=(8,8),
                       cells_per_block=(2,2), visualize=True, feature_vector=True)
    return fd

# ORB-based descriptor: produce a fixed-length vector by taking mean of descriptors (if any)
orb = cv2.ORB_create(nfeatures=500)
def extract_orb_feature_gray(img, resize=(128,128), orb=orb, out_dim=256):
    im = cv2.resize(img, resize)
    gray = cv2.cvtColor(im, cv2.COLOR_RGB2GRAY)
    kps, des = orb.detectAndCompute(gray, None)
    if des is None:
        return np.zeros(out_dim, dtype=np.float32)
    # flatten by mean pooling across keypoint descriptors then pad/cut to out_dim
    vec = des.mean(axis=0)
    if len(vec) >= out_dim:
        return vec[:out_dim]
    else:
        res = np.zeros(out_dim, dtype=np.float32)
        res[:len(vec)] = vec
        return res

# Build feature matrix (HOG + ORB concatenated)
X_feats = []
y_labels = []
print("\nExtracting classical features (this may take a while)...")
for i, p in enumerate(img_paths):
    img = cv2.imread(p)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    hog_f = extract_hog_feature_gray(img)
    orb_f = extract_orb_feature_gray(img)
    feat = np.concatenate([hog_f, orb_f])
    X_feats.append(feat)
    y_labels.append(labels[i])
    if (i+1) % 200 == 0:
        print(f"  extracted features from {i+1} images")

X_feats = np.vstack(X_feats)
print("Feature matrix shape (hog+orb):", X_feats.shape)

# Dimensionality reduction (PCA) to speed up SVM
pca = PCA(n_components=128, random_state=42)
X_pca = pca.fit_transform(X_feats)
print("After PCA shape:", X_pca.shape)

# Train-test split and SVM classifier
X_train, X_test, y_train, y_test = train_test_split(X_pca, y_labels, test_size=0.2, random_state=42, stratify=y_labels)
print("\nTraining SVM (classical features) ...")
svm = SVC(kernel='rbf', probability=False, verbose=False)
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print(f"Classical features (HOG+ORB + PCA + SVM) accuracy on test subset: {acc*100:.2f}%")
print("\nClassification report (classical features):")
print(classification_report(y_test, y_pred, zero_division=0, digits=4))

# === 5) MODULE 3: Deep learning with transfer learning (EfficientNetB0) ===
# We'll use ImageDataGenerator with flow_from_directory pointing at chosen_root.
BATCH_SIZE = 32
IMG_SIZE = (224,224)

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=25,
    width_shift_range=0.12,
    height_shift_range=0.12,
    zoom_range=0.15,
    brightness_range=(0.6,1.4),
    horizontal_flip=True,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    chosen_root, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical', subset='training', shuffle=True
)
val_generator = train_datagen.flow_from_directory(
    chosen_root, target_size=IMG_SIZE, batch_size=BATCH_SIZE, class_mode='categorical', subset='validation', shuffle=False
)

print("\nNumber of classes detected:", train_generator.num_classes)

# Build model: EfficientNetB0 base + small head
base = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3))
base.trainable = False  # freeze base for transfer learning first

model = models.Sequential([
    base,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.3),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(train_generator.num_classes, activation='softmax')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

# Train for a few epochs (can increase if time allows)
EPOCHS = 6
print(f"\nStarting training for {EPOCHS} epochs. This may take several minutes...")
history = model.fit(train_generator, validation_data=val_generator, epochs=EPOCHS)

# Optionally fine-tune: unfreeze some top layers and continue training
print("\nFine-tuning: unfreeze top layers of base model and continue training (small LR).")
base.trainable = True
# Unfreeze only the top block for safe fine-tuning
for layer in base.layers[:-30]:
    layer.trainable = False

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
              loss='categorical_crossentropy',
              metrics=['accuracy'])
ft_epochs = 4
history_ft = model.fit(train_generator, validation_data=val_generator, epochs=ft_epochs)

# Combine history dictionaries for plotting
def plot_training(histories, titles=("Train Accuracy","Train Loss")):
    plt.figure(figsize=(12,4))
    # accuracy
    plt.subplot(1,2,1)
    for h,label in histories:
        plt.plot(h.history['accuracy'], label=f"{label} train acc")
        if 'val_accuracy' in h.history:
            plt.plot(h.history['val_accuracy'], '--', label=f"{label} val acc")
    plt.title("Accuracy"); plt.legend(); plt.grid(True)
    # loss
    plt.subplot(1,2,2)
    for h,label in histories:
        plt.plot(h.history['loss'], label=f"{label} train loss")
        if 'val_loss' in h.history:
            plt.plot(h.history['val_loss'], '--', label=f"{label} val loss")
    plt.title("Loss"); plt.legend(); plt.grid(True)
    plt.show()

plot_training([(history, "base"), (history_ft, "finetune")])

# Evaluate on validation set (as proxy for test)
val_steps = val_generator.samples // val_generator.batch_size + 1
val_generator.reset()
preds = model.predict(val_generator, steps=val_steps, verbose=1)
pred_labels = np.argmax(preds, axis=1)
true_labels = val_generator.classes[:len(pred_labels)]
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
cm = confusion_matrix(true_labels, pred_labels, labels=range(train_generator.num_classes))
plt.figure(figsize=(8,8))
disp = ConfusionMatrixDisplay(cm, display_labels=list(train_generator.class_indices.keys()))
disp.plot(cmap='Blues', xticks_rotation=90)
plt.title("Confusion matrix (validation)")
plt.show()

# Print overall accuracy on validation
val_acc = np.mean(pred_labels == true_labels)
print(f"\nEfficientNetB0 (transfer learning + fine-tune) validation accuracy (approx): {val_acc*100:.2f}%")
print("\nTop-5 predicted class mapping (index -> class):")
inv_map = {v:k for k,v in train_generator.class_indices.items()}
for idx in range( min(10, len(inv_map)) ):
    print(idx, "->", inv_map[idx])

# === 6) Grad-CAM explainability for a sample image from validation ===
# We'll compute Grad-CAM for one example and overlay heatmap.
def make_gradcam_heatmap(img_array, model, last_conv_layer_name, pred_index=None):
    grad_model = tf.keras.models.Model([model.inputs], [model.get_layer(last_conv_layer_name).output, model.output])
    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        if pred_index is None:
            pred_index = tf.argmax(predictions[0])
        class_channel = predictions[:, pred_index]

    grads = tape.gradient(class_channel, conv_outputs)
    pooled_grads = tf.reduce_mean(grads, axis=(0,1,2))
    conv_outputs = conv_outputs[0]
    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap, 0) / (tf.math.reduce_max(heatmap) + 1e-8)
    return heatmap.numpy()

# find last conv layer name in model
last_conv_layer_name = None
for layer in reversed(model.layers):
    # some layers are nested, so we try to find the last Conv2D inside base
    if isinstance(layer, tf.keras.layers.Conv2D):
        last_conv_layer_name = layer.name
        break
# if not found at top-level, search base model
if last_conv_layer_name is None:
    for layer in reversed(base.layers):
        if isinstance(layer, tf.keras.layers.Conv2D):
            last_conv_layer_name = layer.name
            break

print("Using last conv layer for Grad-CAM:", last_conv_layer_name)

# pick a sample image from validation directory
val_sample_paths = []
for cls in list(train_generator.class_indices.keys())[:5]:
    p = glob.glob(os.path.join(chosen_root, cls, "*.jpg")) + glob.glob(os.path.join(chosen_root, cls, "*.png"))
    if p:
        val_sample_paths.append(p[0])
if not val_sample_paths:
    print("No sample images for Grad-CAM found.")
else:
    sample_path = val_sample_paths[0]
    orig = tf.keras.preprocessing.image.load_img(sample_path, target_size=IMG_SIZE)
    x = tf.keras.preprocessing.image.img_to_array(orig)
    x = x/255.0
    input_array = np.expand_dims(x, axis=0)

    heatmap = make_gradcam_heatmap(input_array, model, last_conv_layer_name)
    # resize heatmap to image size
    heatmap = cv2.resize(heatmap, (IMG_SIZE[1], IMG_SIZE[0]))
    heatmap = np.uint8(255 * heatmap)
    heatmap_color = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
    img_orig = (x*255).astype("uint8")
    img_orig_bgr = cv2.cvtColor(img_orig, cv2.COLOR_RGB2BGR)
    superimposed = cv2.addWeighted(img_orig_bgr, 0.6, heatmap_color, 0.4, 0)
    superimposed_rgb = cv2.cvtColor(superimposed, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(8,4))
    plt.subplot(1,2,1); plt.imshow(img_orig.astype(int)); plt.title("Original"); plt.axis('off')
    plt.subplot(1,2,2); plt.imshow(superimposed_rgb); plt.title("Grad-CAM Overlay"); plt.axis('off')
    plt.show()

# === 7) Save model and artifacts to a zip for download ===
print("\nSaving trained model and PCA + SVM artifacts for submission...")
OUT_DIR = "/content/output_submission"
if os.path.exists(OUT_DIR):
    shutil.rmtree(OUT_DIR)
os.makedirs(OUT_DIR, exist_ok=True)

# save model
model.save(os.path.join(OUT_DIR, "efficientnet_finetuned.h5"))
# save PCA and SVM using joblib
import joblib
joblib.dump(pca, os.path.join(OUT_DIR, "pca_classical.joblib"))
joblib.dump(svm, os.path.join(OUT_DIR, "svm_classical.joblib"))

# package output
shutil.make_archive("/content/submission_artifacts", 'zip', OUT_DIR)
files.download("/content/submission_artifacts.zip")
print("Artifacts zipped and download prompt should appear. If not, check files in /content/output_submission")